<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>NMaier.SimpleDlna.GUI</RootNamespace>
    <AssemblyName>SimpleDLNA</AssemblyName>
    <AssemblyTitle>SimpleDLNA GUI</AssemblyTitle>
    <Description>Graphical User Interface to SimpleDLNA</Description>
    <ApplicationIcon>sdlna.ico</ApplicationIcon>
    <UseWindowsForms>true</UseWindowsForms>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\fsserver\fsserver.csproj" />
    <ProjectReference Include="..\NMaier.Windows.Forms\NMaier.Windows.Forms.csproj" />
    <ProjectReference Include="..\server\server.csproj" />
    <ProjectReference Include="..\thumbs\thumbs.csproj" />
    <ProjectReference Include="..\util\util.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\**" />
    <None Include="Resources\**" />
  </ItemGroup>

</Project>
