<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>NMaier.SimpleDlna.Utilities</RootNamespace>
    <AssemblyName>SimpleDlna.Utilities</AssemblyName>
    <AssemblyTitle>Utilities class library</AssemblyTitle>
    <UseWindowsForms>false</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>

</Project>
