<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>NMaier.Windows.Forms</RootNamespace>
    <AssemblyName>NMaier.Windows.Forms</AssemblyName>
    <AssemblyTitle>NMaier.Windows.Forms</AssemblyTitle>
    <Description>Various WinForms helpers</Description>
    <Product>NMaier.Windows.Forms</Product>
    <Copyright>Copyright © 2014 Nils Maier</Copyright>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyOriginatorKeyFile>NMaier.Windows.Forms.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

</Project>
