<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>NMaier.SimpleDlna.Thumbnails</RootNamespace>
    <AssemblyName>SimpleDlna.Thumbnails</AssemblyName>
    <AssemblyTitle>Thumbnails class library</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\server\server.csproj" />
    <ProjectReference Include="..\util\util.csproj" />
  </ItemGroup>

</Project>
